[package]
version = "0.1.0"
name = "helios-program"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", tag = "v1.0.1" }
common = { workspace = true  }
consensus-core = { workspace = true }
serde_cbor = { workspace = true }
sp1-helios-primitives = { workspace = true }
alloy-sol-types = {workspace = true}
ssz-rs = { workspace = true }
alloy-primitives = { workspace = true }
hex = { workspace = true }
